name: cicdshka

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup JRE 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
          architecture: x64
          java-package: 'jdk'
          cache: maven
      - name: Build
        run: mvn --batch-mode package
      - name: Cache jar
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: target/hueBot-jar-with-dependencies.jar
  deploy:
    needs: build
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: jar
          path: target
      - name: Init SSH
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_SECRET }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -av target/hueBot-jar-with-dependencies.jar ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/opt/bot
      - name: Reload service
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'sudo systemctl restart bot.service'
