name: cicdshka

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup JRE 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
          architecture: x64
          java-package: 'jre'
          cache: maven
      - name: Build
        run: mvn --batch-mode package
